version: "3"

services:
  mongodb:
    extends:
      file: docker-compose.database.yml
      service: mongodb

  app:
    image: app-local
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3333:3333
    depends_on:
      - mongodb
    env_file:
      - .env.example
    environment:
      - MONGO_URL=mongodb://mongodb:27017/objective_nodejs
