name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  tests:
    name: e2e tests docker
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Start database
      run: docker-compose -f docker-compose.e2e-test.yml up --build

    - name: Stop containers
      if: always()
      run: docker-compose down
