name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  tests:
    name: e2e tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Start database
      run: docker-compose -f docker-compose.database.yml up -d

    - uses: actions/setup-node@v2
      with:
        node-version: "18"
        cache: 'npm'
    - run: cp .env.example .env
    - run: npm ci

    - name: Run tests
      run: npm run test:e2e

    - name: Stop containers
      if: always()
      run: docker-compose down
