name: Unit tests

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  tests:
    name: Unit tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: "18"
        cache: 'npm'
    - run: cp .env.example .env
    - run: npm ci

    - name: Run tests
      run: npm run test
